# pyright: reportArgumentType=false, reportAttributeAccessIssue=false, reportOptionalMemberAccess=false, reportCallIssue=false, reportIndexIssue=false
"""Tests for the OpenRouter Web Tools filter: documented engine coverage,
max_characters support, and standalone-vs-embedded source parity.

The pipe ships TWO copies of this filter: the standalone reference at
filters/openrouter_web_tools.py and the canonical embedded copy generated by
FilterManager.render_openrouter_web_tools_filter_source(). Production runs the
embedded copy, so behavioural tests exercise the generated source; the parity
test guarantees the two never drift.
"""
from __future__ import annotations

import sys
from pathlib import Path
from types import ModuleType

from open_webui_openrouter_pipe.filters.filter_manager import FilterManager

_STANDALONE_PATH = Path(__file__).resolve().parents[1] / "filters" / "openrouter_web_tools.py"


def _load_filter_from_source(source: str, module_name: str) -> ModuleType:
    if "open_webui.env" not in sys.modules:
        env_mock = ModuleType("open_webui.env")
        env_mock.SRC_LOG_LEVELS = {}  # type: ignore[attr-defined]
        sys.modules["open_webui.env"] = env_mock

    module = ModuleType(module_name)
    module.__file__ = f"<{module_name}_rendered_source>"
    sys.modules[module_name] = module
    exec(compile(source, f"<{module_name}>", "exec"), module.__dict__)
    module.Filter.UserValves.model_rebuild()
    module.Filter.Valves.model_rebuild()
    return module


def _embedded_module() -> ModuleType:
    source = FilterManager.render_openrouter_web_tools_filter_source()
    return _load_filter_from_source(source, "_embedded_web_tools_filter")


def test_web_search_engine_accepts_perplexity():
    """web_search documents a `perplexity` engine; the filter must accept it."""
    module = _embedded_module()
    valves = module.Filter.Valves(WEB_SEARCH_ENGINE="perplexity")
    assert valves.WEB_SEARCH_ENGINE == "perplexity"


def test_web_fetch_engine_accepts_parallel():
    """web_fetch documents a `parallel` engine; the filter must accept it."""
    module = _embedded_module()
    valves = module.Filter.Valves(WEB_FETCH_ENGINE="parallel")
    assert valves.WEB_FETCH_ENGINE == "parallel"


def test_web_search_max_characters_emitted_in_server_tools():
    """A configured WEB_SEARCH_MAX_CHARACTERS cap must reach the web_search params."""
    module = _embedded_module()
    f = module.Filter()
    f.valves.WEB_SEARCH_MAX_CHARACTERS = 5000
    meta: dict = {}
    f.inlet({}, __metadata__=meta, __user__={"valves": module.Filter.UserValves()})
    ws = meta["openrouter_pipe"]["server_tools"]["web_search"]
    assert ws["max_characters"] == 5000


def test_web_search_max_characters_omitted_when_zero():
    """Default (0) max_characters must not be emitted."""
    module = _embedded_module()
    f = module.Filter()
    meta: dict = {}
    f.inlet({}, __metadata__=meta, __user__={"valves": module.Filter.UserValves()})
    ws = meta["openrouter_pipe"]["server_tools"]["web_search"]
    assert "max_characters" not in ws


def test_no_server_tools_written_when_all_toggles_off():
    """Access model: with every per-tool toggle off, the filter writes NO server tools.

    Tool access is gated by filter attach + per-tool toggles (admins grant the filter;
    users flip toggles) — not by model capability. Nothing enabled => nothing injected.
    """
    module = _embedded_module()
    user_valves = module.Filter.UserValves(WEB_SEARCH=False, WEB_FETCH=False, DATETIME=False)
    meta: dict = {}
    module.Filter().inlet({}, __metadata__=meta, __user__={"valves": user_valves})
    assert not meta.get("openrouter_pipe", {}).get("server_tools")


def test_standalone_and_embedded_web_tools_filter_are_identical():
    """The standalone reference filter must equal the generated embedded source.

    Guards against drift: any field added to one copy must be added to the other.
    """
    standalone = _STANDALONE_PATH.read_text(encoding="utf-8")
    embedded = FilterManager.render_openrouter_web_tools_filter_source(
        enable_web_search=True,
        enable_web_fetch=True,
        enable_datetime=True,
    )
    assert embedded.strip() == standalone.strip()
