# pyright: reportArgumentType=false, reportAttributeAccessIssue=false, reportOptionalMemberAccess=false, reportCallIssue=false, reportIndexIssue=false
"""Tests for the OpenRouter Web Tools filter: documented engine coverage,
max_characters support, and standalone-vs-embedded source parity.

The pipe ships TWO copies of this filter: the standalone reference at
filters/openrouter_web_tools.py and the canonical embedded copy generated by
FilterManager.render_openrouter_web_tools_filter_source(). Production runs the
embedded copy, so behavioural tests exercise the generated source; the parity
test guarantees the two never drift.
"""
from __future__ import annotations

import sys
from pathlib import Path
from types import ModuleType

import pytest

from open_webui_openrouter_pipe.filters.filter_manager import FilterManager

_STANDALONE_PATH = Path(__file__).resolve().parents[1] / "filters" / "openrouter_web_tools.py"


def _load_filter_from_source(source: str, module_name: str) -> ModuleType:
    if "open_webui.env" not in sys.modules:
        env_mock = ModuleType("open_webui.env")
        env_mock.SRC_LOG_LEVELS = {}  # type: ignore[attr-defined]
        sys.modules["open_webui.env"] = env_mock

    module = ModuleType(module_name)
    module.__file__ = f"<{module_name}_rendered_source>"
    sys.modules[module_name] = module
    exec(compile(source, f"<{module_name}>", "exec"), module.__dict__)
    module.Filter.UserValves.model_rebuild()
    module.Filter.Valves.model_rebuild()
    return module


def _embedded_module() -> ModuleType:
    source = FilterManager.render_openrouter_web_tools_filter_source()
    return _load_filter_from_source(source, "_embedded_web_tools_filter")


def test_web_search_engine_accepts_perplexity():
    """web_search documents a `perplexity` engine; the filter must accept it."""
    module = _embedded_module()
    valves = module.Filter.Valves(WEB_SEARCH_ENGINE="perplexity")
    assert valves.WEB_SEARCH_ENGINE == "perplexity"


def test_web_fetch_engine_accepts_parallel():
    """web_fetch documents a `parallel` engine; the filter must accept it."""
    module = _embedded_module()
    valves = module.Filter.Valves(WEB_FETCH_ENGINE="parallel")
    assert valves.WEB_FETCH_ENGINE == "parallel"


def test_web_search_max_characters_emitted_in_server_tools():
    """A configured WEB_SEARCH_MAX_CHARACTERS cap must reach the web_search params."""
    module = _embedded_module()
    f = module.Filter()
    f.valves.WEB_SEARCH_MAX_CHARACTERS = 5000
    meta: dict = {}
    f.inlet({}, __metadata__=meta, __user__={"valves": module.Filter.UserValves()})
    ws = meta["openrouter_pipe"]["server_tools"]["web_search"]
    assert ws["max_characters"] == 5000


def test_web_search_max_characters_omitted_when_zero():
    """Default (0) max_characters must not be emitted."""
    module = _embedded_module()
    f = module.Filter()
    meta: dict = {}
    f.inlet({}, __metadata__=meta, __user__={"valves": module.Filter.UserValves()})
    ws = meta["openrouter_pipe"]["server_tools"]["web_search"]
    assert "max_characters" not in ws


def test_no_server_tools_written_when_all_toggles_off():
    """Access model: with every per-tool toggle off, the filter writes NO server tools.

    Tool access is gated by filter attach + per-tool toggles (admins grant the filter;
    users flip toggles) — not by model capability. Nothing enabled => nothing injected.
    """
    module = _embedded_module()
    user_valves = module.Filter.UserValves(WEB_SEARCH=False, WEB_FETCH=False, DATETIME=False)
    meta: dict = {}
    module.Filter().inlet({}, __metadata__=meta, __user__={"valves": user_valves})
    assert not meta.get("openrouter_pipe", {}).get("server_tools")


def test_advisor_toggle_emits_advisor_server_tool():
    module = _embedded_module()
    f = module.Filter()
    f.valves.ADVISOR_MODEL = "~anthropic/claude-opus-latest"
    user_valves = module.Filter.UserValves(WEB_SEARCH=False, DATETIME=False, ADVISOR=True)
    meta: dict = {}
    f.inlet({}, __metadata__=meta, __user__={"valves": user_valves})
    st = meta["openrouter_pipe"]["server_tools"]
    assert st["advisor"] == {"model": "~anthropic/claude-opus-latest"}


def test_advisor_without_model_emits_empty_params():
    """No advisor model set => empty params (OpenRouter falls back to outer model)."""
    module = _embedded_module()
    f = module.Filter()
    user_valves = module.Filter.UserValves(WEB_SEARCH=False, DATETIME=False, ADVISOR=True)
    meta: dict = {}
    f.inlet({}, __metadata__=meta, __user__={"valves": user_valves})
    assert meta["openrouter_pipe"]["server_tools"]["advisor"] == {}


def test_subagent_toggle_emits_subagent_server_tool():
    module = _embedded_module()
    f = module.Filter()
    f.valves.SUBAGENT_MODEL = "~anthropic/claude-haiku-latest"
    user_valves = module.Filter.UserValves(WEB_SEARCH=False, DATETIME=False, SUBAGENT=True)
    meta: dict = {}
    f.inlet({}, __metadata__=meta, __user__={"valves": user_valves})
    st = meta["openrouter_pipe"]["server_tools"]
    assert st["subagent"] == {"model": "~anthropic/claude-haiku-latest"}


def test_search_models_toggle_emits_chat_search_models():
    module = _embedded_module()
    f = module.Filter()
    user_valves = module.Filter.UserValves(WEB_SEARCH=False, DATETIME=False, SEARCH_MODELS=True)
    meta: dict = {}
    f.inlet({}, __metadata__=meta, __user__={"valves": user_valves})
    assert meta["openrouter_pipe"]["server_tools"]["chat_search_models"] == {}


def test_cost_guard_writes_stop_server_tools_when():
    module = _embedded_module()
    f = module.Filter()
    f.valves.SERVER_TOOLS_MAX_COST_USD = 0.5
    user_valves = module.Filter.UserValves(WEB_SEARCH=False, DATETIME=False, ADVISOR=True)
    meta: dict = {}
    f.inlet({}, __metadata__=meta, __user__={"valves": user_valves})
    assert meta["openrouter_pipe"]["stop_server_tools_when"] == [
        {"type": "max_cost", "max_cost_in_dollars": 0.5}
    ]


def test_cost_guard_absent_when_unset():
    module = _embedded_module()
    f = module.Filter()
    user_valves = module.Filter.UserValves(WEB_SEARCH=False, DATETIME=False, ADVISOR=True)
    meta: dict = {}
    f.inlet({}, __metadata__=meta, __user__={"valves": user_valves})
    assert "stop_server_tools_when" not in meta.get("openrouter_pipe", {})


def test_standalone_and_embedded_web_tools_filter_are_identical():
    """The standalone reference filter must equal the generated embedded source.

    Guards against drift: any field added to one copy must be added to the other.
    """
    standalone = _STANDALONE_PATH.read_text(encoding="utf-8")
    embedded = FilterManager.render_openrouter_web_tools_filter_source(
        enable_web_search=True,
        enable_web_fetch=True,
        enable_datetime=True,
    )
    assert embedded.strip() == standalone.strip()


def _standalone_pairs():
    """Every filters/*.py paired with the renderer that installs it, by MARKER.

    Discovered, not enumerated. The previous version listed two filenames in a
    parametrize and covered the third by hand, so a fourth reference filter would be
    silently unguarded from the moment it was added — which is exactly how the
    direct-uploads pair drifted 24 lines apart, with the un-hardened copy being the one
    the pipe auto-installs for everyone.
    """
    renderers = {
        "render_openrouter_web_tools_filter_source": {
            "enable_web_search": True, "enable_web_fetch": True, "enable_datetime": True
        },
        "render_openrouter_image_gen_filter_source": {"dedicated_image_api": True},
        "render_direct_uploads_filter_source": {},
    }
    rendered = {
        name: getattr(FilterManager, name)(**kwargs) for name, kwargs in renderers.items()
    }

    pairs, unmapped = [], []
    for path in sorted(_STANDALONE_PATH.parent.glob("*.py")):
        text = path.read_text(encoding="utf-8")
        marker = None
        for line in text.splitlines():
            if line.startswith("OWUI_OPENROUTER_PIPE_MARKER"):
                marker = line.split("=", 1)[1].strip().strip('"').strip("'")
                break
        if not marker:
            unmapped.append(f"{path.name}: no OWUI_OPENROUTER_PIPE_MARKER")
            continue
        matches = [name for name, src in rendered.items() if marker in src]
        if len(matches) != 1:
            unmapped.append(f"{path.name}: marker {marker!r} matched {matches or 'no'} renderer(s)")
            continue
        pairs.append((path.name, matches[0], renderers[matches[0]]))
    return pairs, unmapped


def test_every_standalone_filter_is_mapped_to_a_renderer():
    """An unmapped file is loud rather than absent.

    Without this, adding filters/openrouter_something.py with no matching renderer
    simply drops out of the comparison below and nobody finds out.
    """
    pairs, unmapped = _standalone_pairs()
    assert not unmapped, (
        "these files under filters/ are not paired with any renderer, so nothing "
        f"compares them to the source the pipe installs: {unmapped}"
    )
    assert len(pairs) >= 3, (
        f"only {len(pairs)} standalone filters were discovered; the sweep has stopped "
        "finding them and the comparison below is checking almost nothing"
    )


@pytest.mark.parametrize(
    ("filename", "renderer", "kwargs"),
    _standalone_pairs()[0],
    ids=lambda v: v if isinstance(v, str) else "",
)
def test_every_standalone_filter_matches_its_generator(filename, renderer, kwargs):
    """The reference copy in filters/ and the source the pipe installs must agree.

    The direct-uploads pair had drifted 24 lines apart with nothing to notice: the
    reference had been hardened (a guarded SRC_LOG_LEVELS import, and getattr defaults
    for four UserValves) while the generator -- the copy actually installed into Open
    WebUI for everyone who lets the pipe auto-install -- kept the form that raises
    AttributeError on a UserValves object missing those fields.
    """
    standalone = (_STANDALONE_PATH.parent / filename).read_text(encoding="utf-8")
    generated = getattr(FilterManager, renderer)(**kwargs)
    assert generated.strip() == standalone.strip(), (
        f"filters/{filename} and FilterManager.{renderer} have diverged. Whichever "
        "copy you changed, apply it to the other -- users get one or the other "
        "depending on whether they installed it by hand or let the pipe do it."
    )
